# Generated by Django 2.0.5 on 2018-07-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Item', verbose_name='商品')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['-id'],
            },
        ),
    ]
